services:
  postgres:
    image: "postgres:17"
    ports:
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate_db:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: "1"
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/postgres"
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "alembic upgrade head"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      PYTHONUNBUFFERED: "1"
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/postgres"
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    name: postgres_data_bank