"""add version column to account table

Revision ID: 12f47c2bc52e
Revises: ebefd2df472a
Create Date: 2025-04-13 22:04:28.029149

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12f47c2bc52e"
down_revision: Union[str, None] = "ebefd2df472a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("version", sa.Integer(), server_default=sa.text("0"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account", "version")
    # ### end Alembic commands ###
