"""add amount column to account table

Revision ID: ebefd2df472a
Revises: ffeec1757860
Create Date: 2025-04-12 23:09:02.770249

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ebefd2df472a"
down_revision: Union[str, None] = "ffeec1757860"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account", sa.Column("amount", sa.Numeric(precision=24, scale=8), server_default=sa.text("0"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account", "amount")
    # ### end Alembic commands ###
