"""add transaction table

Revision ID: ffeec1757860
Revises: e34520309e41
Create Date: 2025-04-12 22:04:11.923611

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = "ffeec1757860"
down_revision: Union[str, None] = "e34520309e41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

transaction_status_enum = postgresql.ENUM("pending", "completed", "canceled", "failed", name="transaction_status")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column(
            "created",
            sqlalchemy_utils.types.arrow.ArrowType(),
            server_default=sa.text("(now() at time zone 'utc')"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sqlalchemy_utils.types.arrow.ArrowType(),
            server_default=sa.text("(now() at time zone 'utc')"),
            nullable=False,
        ),
        sa.Column("archived", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("from_account_id", sa.UUID(), nullable=False),
        sa.Column("to_account_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("status", transaction_status_enum, server_default="pending", nullable=False),
        sa.ForeignKeyConstraint(
            ["from_account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction")

    transaction_status_enum.drop(bind=op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
